# Server Port
server.port=9090

# Application Name
spring.application.name=api-gateway

# Register with Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Enable dynamic discovery-based routing
spring.cloud.gateway.discovery.locator.enabled=true

# Force service IDs in lowercase for routing paths (e.g. /account-service/accounts/123)
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
