-- Schema definition for banking system tables

CREATE TABLE Customers (
    CustomerID NUMBER PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    DOB DATE,
    Balance NUMBER DEFAULT 0,
    LastModified DATE DEFAULT SYSDATE,
    IsVIP VARCHAR2(5) DEFAULT 'FALSE' CHECK (IsVIP IN ('TRUE', 'FALSE'))
);

CREATE TABLE Accounts (
    AccountID NUMBER PRIMARY KEY,
    CustomerID NUMBER,
    AccountType VARCHAR2(20) CHECK (AccountType IN ('Savings', 'Checking')),
    Balance NUMBER DEFAULT 0,
    LastModified DATE DEFAULT SYSDATE,
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);

CREATE TABLE Transactions (
    TransactionID NUMBER PRIMARY KEY,
    AccountID NUMBER,
    TransactionDate DATE DEFAULT SYSDATE,
    Amount NUMBER NOT NULL,
    TransactionType VARCHAR2(10) CHECK (TransactionType IN ('Deposit', 'Withdrawal')),
    FOREIGN KEY (AccountID) REFERENCES Accounts(AccountID)
);

CREATE TABLE Loans (
    LoanID NUMBER PRIMARY KEY,
    CustomerID NUMBER,
    LoanAmount NUMBER NOT NULL,
    InterestRate NUMBER NOT NULL,
    StartDate DATE DEFAULT SYSDATE,
    EndDate DATE NOT NULL,
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);

CREATE TABLE Employees (
    EmployeeID NUMBER PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Position VARCHAR2(50),
    Salary NUMBER,
    Department VARCHAR2(50),
    HireDate DATE DEFAULT SYSDATE
);

-- Audit log table for transaction trigger
CREATE TABLE AuditLog (
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TransactionID NUMBER,
    ActionDate DATE DEFAULT SYSDATE,
    ActionType VARCHAR2(20),
    Amount NUMBER
);
